### ISSUE TITLE
Improve Code-A-Pookalam Readme.md

### ISSUE THREAD

**Issue by foss-cell-mec** [FossMec/Code-A-Pookalam23#1]
## Note
The readme should contain the description of Code-a-pookalam, the guidelines and resources to get started, the prize pool, and the point of contact. These details can be found on our [website](https://codeapookalam.super.site/).
You can also add anything as per your creative level.
Also, refer to our previous [Code-a-pookalam'22](https://github.com/FossMec/Code-a-pookalam-2022) repository to get an idea of how readme file is made.

If you're interested, do comment here, ping @karthikgkumar and @foss-cell-mec.

**Comment by n1ved** [comment]
@karthikgkumar  @foss-cell-mec I'm interested in doing this

**Comment by karthikgkumar** [comment]
Yes! Please go forward!
I'm assigning you this. Please do complete it by 31 Aug.

**Comment by n1ved** [comment]
@karthikgkumar I've created a PR please review

**Comment by foss-cell-mec** [comment]
Good work! I'm closing this issue.
