### ISSUE TITLE
Send Periodic mails for participants

### ISSUE THREAD

**Issue by karthikgkumar** [FossMec/Code-A-Pookalam23#3]
# Event 
Send  a mail to all participants with the details of submission. Attach the link on how to do the PR. Details are given in the website.
Also, the partcipants must upload their pookalam picture in the gform that's been sent through the mail. Do prepare that also.
Please do finish it by 1st Sep. 
Send a remainder submission email on or before 4th Sep

**Comment by nehakoshti** [comment]
Hey,
I wanna submit my code. But as you mentioned above, no such mail has been received yet. Can you look into it please.

**Comment by roshinjimmy** [comment]
Hello Neha,

Thank you for reaching out. We have sent a mail containing instructions for
submission now. If you have any further questions or need assistance,
please don't hesitate to let us know.

Best Regards

**Comment by foss-cell-mec** [comment]
Dear Neha,
The mail had been sent on that day itself. Please do check your inbox.
